### ISSUE TITLE
Fix rendering of README on crates.io

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/rust-ieee802.15.4#15]
The second-to-last line of the README doesn't render on crates.io. I suspect this is due to the `<br />` tag, and might be fixed by adding a space before it.

Not urgent, but should be handled with the next release.

**Comment by djovercash** [comment]
May I take this issue?

**Comment by hannobraun** [comment]
@djovercash Of course, go ahead!

**Comment by djovercash** [comment]
Thank you! Is there a way to test the change on crates.io before pushing up a PR, or should I go ahead and push up the PR, and you'll test on your end?

**Comment by hannobraun** [comment]
Well, thank you for being willing to do the work!

I can think of two ways to test this:
1. Figure out which Markdown implementation is used by crates.io, use that to verify the fix.
2. Just wait for the next release, see if the fix worked, keep repeating until it does.

Since this is a low-impact problem, I think option 2 is more than enough.

**Comment by djovercash** [comment]
Wonderful! I'll push up the PR. Thank you for letting me contribute and hopefully it works

**Comment by hannobraun** [comment]
Potential fix was merged in #16. I'll leave this open until we can confirm that was actually the issue.

@djovercash 
> Thank you for letting me contribute and hopefully it works

You don't have to thank me for that :-)
Contributions are always welcome. Thank you!

**Comment by hannobraun** [comment]
The problem has been solved! Closing.
