### ISSUE TITLE
Latest version depends on `alloc` via `BufMut`

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/rust-ieee802.15.4#33]
The [switch to `BufMut`](https://github.com/braun-embedded/rust-ieee802.15.4/pull/28) has introduced an accidental dependency on `alloc`. See https://github.com/braun-embedded/rust-dw1000/pull/124#issuecomment-758220554.

This is certainly bad, and needs to be fixed in one way or the other. Is there a way to salvage this situation, or do we need to revert #28?

cc @xoac

**Comment by hannobraun** [comment]
It looks like `BufMut` uses its `alloc` imports only to implement the trait for some `alloc` types. I haven't looked at the rest of the `bytes` crate, but it might be straight-forward to hide this behind a feature flag, allowing us to keep using `bytes` without changes.

**Comment by xoac** [comment]
I don't know a way to hide `alloc` from dependent crate (bytes). This is sth what `bytes` can only do as far as I know. I think this could be introduced with minor change in `bytes` if they agree that alloc can be optional.

**Comment by hannobraun** [comment]
Yes, that is what I meant: Modify `bytes` to add the feature flag there.
