### ISSUE TITLE
Latest version doesn't compile on arm-thumbv6m targets

### ISSUE THREAD

**Issue by henrikssn** [braun-embedded/rust-ieee802.15.4#34]
This is due to the dependency on bytes. The workaround (using nightly compiler and patching their code) isn't really acceptable IMO.

See https://github.com/tokio-rs/bytes/issues/461

**Comment by hannobraun** [comment]
Thanks for opening this issue, @henrikssn!

This is the second serious issue related to `bytes` (see #33), and it seems like this one isn't a straight-forward fix. I'm open to suggestions, but maybe the solution is to revert #28. For now, I recommend using version 0.3 (which doesn't depend on `bytes`) as a workaround.

cc @xoac
