### ISSUE TITLE
Supporting security on MAC layer with current `byte::TryRead` interface is not possible.

### ISSUE THREAD

**Issue by datdenkikniet** [braun-embedded/rust-ieee802.15.4#37]
I'm implementing the security features specified by the 802.15.4 standard for this crate. Implementing the procedures by themselves and encrypting outgoing frames is working as expected, but I've run into a bit of a roadblock when it comes to decrypting incoming frames using the current interface. You can find the progress [here](https://github.com/datdenkikniet/rust-ieee802.15.4).

Because `byte::TryRead::try_read` only takes an immutable buffer, we can't perform in-place unsecuring of the payload, and because it is a reference in `Frame`, we can't create a copy of the secured data, unsecure it, and reassign the payload (which would be rather undesirable anyways for performance reasons). 

In my solution, I've implemented `Frame::try_read_with_unsecure` that takes an `&mut [u8]` instead. It works fine, but doesn't fit into the currently used interface (since it expects a `&mut [u8]` for reading) [here](https://github.com/datdenkikniet/rust-ieee802.15.4/blob/security_features/src/mac/frame/mod.rs#L267). 

I'm not sure if there is a better way to do this, or what kind of redesign it would require to remake this.

**Comment by hannobraun** [comment]
Oh man, it seems like we've fallen into an endless cycle of introducing architectural problems while fixing previous architectural problems :smile: 

I haven't had a chance to look into your pull request yet, but I think the solution you're presenting here sounds fine. It would be nice to have to have a unified interface that works for all cases, but if that stands in the way of supporting desirable features, then I'd rather have the features.

If you (or anyone else) has any ideas for a better overall architecture, that would be great (I don't have any, currently). If not, let's just make it work somehow. Maybe someone will come up with a better approach later.

**Comment by datdenkikniet** [comment]
This issue is no longer particularly relevant. A solution has been created (in the form of an additional function that takes a `mut &[u8]`), and it's close enough.
