### ISSUE TITLE
Transferring this repository to Rust IoT

### ISSUE THREAD

**Issue by hannobraun** [braun-embedded/rust-ieee802.15.4#45]
I've decided to transfer this repository to [Rust IoT](https://github.com/rust-iot), who have offered to maintain it. This issue exists to document that this transfer is happening, provide a place to discuss it, and a place to ping anyone who might be interested.

Since I haven't used this library in a long time, and what little IEEE 802.15.4 knowledge I had has degraded in the years since, I'm happy to retire as a maintainer, and have a group with a more active interest take over.

cc @henrikssn and @ryankurte of Rust IoT, who I've been discussing this with on Rust IoT's Matrix channel.

cc @blueluna and @jamesmunns, who have write access to this repository, but haven't been active in a long time.

**Comment by hannobraun** [comment]
I attempted to transfer this repository to Rust IoT, but I need permission to create public repositories in that org to do that.

I also tried to add `rust-iot/core` on crates.io, as @ryankurte advised on Matrix, but got an error stating that this team doesn't exist.

**Comment by henrikssn** [comment]
> I attempted to transfer this repository to Rust IoT, but I need permission to create public repositories in that org to do that.

@ryankurte could you please (temporarily?) add Hanno to `rust-iot/core`? It doesn't seem like I have the permission to do so.

> 
> I also tried to add `rust-iot/core` on crates.io, as @ryankurte advised on Matrix, but got an error stating that this team doesn't exist.

Try adding `github:rust-iot:core`.

**Comment by hannobraun** [comment]
> Try adding `github:rust-iot:core`.

That's what I did. Just retried, same result.

![Screenshot from 2021-11-15 18-49-04](https://user-images.githubusercontent.com/85732/141830029-99b5f280-e0ea-40c3-ba33-3ec2c8821512.png)

**Comment by ryankurte** [comment]
> @ryankurte could you please (temporarily?) add Hanno to rust-iot/core? 

done! i guess the other option in future is to add one of us to the repo to effect this.

> That's what I did. Just retried, same result.

iinteresting, i did this on the CLI, using `cargo owner --add github:rust-iot:core`. maybe it's not available through the web?

**Comment by henrikssn** [comment]
> > That's what I did. Just retried, same result.
> 
> iinteresting, i did this on the CLI, using `cargo owner --add github:rust-iot:core`. maybe it's not available through the web?

It definitely worked for me through the UI so I bet you need to be part of the team to be able to add it (maybe a visibility issue?).

**Comment by hannobraun** [comment]
> I bet you need to be part of the team to be able to add it (maybe a visibility issue?)

That was probably it; it worked this time. The team has been added as an owner.

I didn't remove myself as owner, for the time being. I vaguely remember that there was some limitation on what teams can do on crates.io. I don't remember what it was, but I think it's desirable to have one "human" owner on crates.io, for that forgotten reason. Feel free to remove me, once someone else has been added in addition to the team.

---

The repository has also been transferred. Feel free to remove me from the team again.

**Comment by hannobraun** [comment]
The transfer has happened. Closing.
